// <auto-generated />
using System;
using C_TalentLens.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C_TalentLens.Infrastructure.Migrations
{
    [DbContext(typeof(TalentLensDbContext))]
    [Migration("20260817102900_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("C_TalentLens.Domain.ActionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("ActionItem");
                });

            modelBuilder.Entity("C_TalentLens.Domain.Bottleneck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("Bottleneck");
                });

            modelBuilder.Entity("C_TalentLens.Domain.Requisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("AdvertisementDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ClosedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOpened")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("FilledGoal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HiringGoal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HiringManager")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("OfferExtendedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recruiter")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequisitionCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionCode")
                        .IsUnique();

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("C_TalentLens.Domain.StageTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExitedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("StageTransition");
                });

            modelBuilder.Entity("C_TalentLens.Domain.ActionItem", b =>
                {
                    b.HasOne("C_TalentLens.Domain.Requisition", null)
                        .WithMany("ActionItems")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C_TalentLens.Domain.Bottleneck", b =>
                {
                    b.HasOne("C_TalentLens.Domain.Requisition", null)
                        .WithMany("Bottlenecks")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C_TalentLens.Domain.StageTransition", b =>
                {
                    b.HasOne("C_TalentLens.Domain.Requisition", null)
                        .WithMany("StageHistory")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C_TalentLens.Domain.Requisition", b =>
                {
                    b.Navigation("ActionItems");

                    b.Navigation("Bottlenecks");

                    b.Navigation("StageHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
